module.exports = {
    PRODUCTS: "/products",
    PRODUCT_ID: "/product/:id",
    PRODUCT_EDIT_ID: "/product/edit/:id",
    SERVICES: "/services",
    SERVICE_ID: "/service/:id",
    SERVICE_EDIT_ID: "/service/edit/:id",
    STOCKS: "/stocks",
    STOCK_ID: "/stock/:id",
    STOCK_EDIT_ID: "/stock/edit/:id",
    DELIVERIES: "/deliveries",
    DELIVERY_ID: "/delivery/:id",
    DELIVERY_EDIT_ID: "/delivery/edit/:id",
    TRANSACTION: "/transactions",
    INVENTORY: "/inventories",
    USER:"/users",
    EQUIPMENT:"/equipments",
    EQUIPMENT_ID:"/equipment/:id",
    EQUIPMENT_EDIT_ID:"/equipment/edit/:id",
    LOGBOOK:"/logbooks",
    LOGBOOK_ID:"/logbook/:id",
    LOGBOOK_EDIT_ID:"/logbook/edit/:id",
    REPORTS: "/reports",
    REPORT_ID: "/report/:id",
    REPORT_EDIT_ID: "/report/edit/:id",
    TYPE_CHARTS: "/charts/type",
}